# Extract - Downloaded datasets from 
[500 Cities: Census Tract-level Data (GIS Friendly Format), 2018 release | Chronic Disease and Health Promotion Data & Indicators](https://chronicdata.cdc.gov/500-Cities/)

[County Health Rankings & Roadmaps](https://www.countyhealthrankings.org/explore-health-rankings)

# Transfom - Sausage Making

### Much went into generating these two CSV files from the downloaded Excel and CSV files.  Tears were shed, blood split, carpal tunnel aggravated ...

In [3]:
import pandas as pd
# Read in County-Level csv and convert to ready-to-use dataframe.
path_to_county_data = './County_Level_Data.csv'
county_df = pd.read_csv(path_to_county_data)
# Read in State-Level csv and convert to ready-to-use dataframe.
path_to_state_data = './State_Level_Data.csv'
state_df = pd.read_csv(path_to_state_data)
# Read in County health indicators
path_to_all_counties = './county_health_rankings_data.csv'
all_df = pd.read_csv(path_to_all_counties)

In [4]:
county_df.head()

,State,County,FIPS State,FIPS County,N of CDC Rows,Population2010,Lack Health Insurance,Arthritis,Binge Drinking,High Blood Pressure,...,Diabetes Prevalence,% Food Insecure,% Limited Access,Drug Overdose Mortality Rate,Household Income,Population,% < 18,% 65 and over,% Female,% Rural
0,Alabama,Jefferson,1,1073,105,268987,17.623644,28.116980,14.083346,41.157573,...,12.9,127630,12.27159061,27.21286265,50109,659521,23.019282,15.062750,52.675957,9.833765
1,Alabama,Limestone,1,1083,2,1521,12.651479,19.969822,18.919132,29.115779,...,12.3,11470,3.518353856,5.81389011,52181,92753,23.039686,14.549395,49.890570,57.609142
2,Alabama,Madison,1,1089,56,178484,14.999397,29.339637,14.031491,37.049979,...,12.3,52210,7.467345123,11.78850479,61193,356967,22.077671,14.384243,51.188205,16.441515
3,Alabama,Mobile,1,1097,75,195045,17.147010,32.241149,14.595537,42.269862,...,14.7,79390,10.2659253,15.17640767,45233,414836,23.700450,15.340038,52.222806,20.020243
4,Alabama,Montgomery,1,1101,60,205733,17.979816,29.418294,14.999920,40.404269,...,13.2,51560,14.57214106,7.363152136,45111,226349,23.224313,14.028337,52.719031,10.491230

In [5]:
state_df.head()

,State,FIPS State,Population2010-State,N of CDC Rows-State,Lack Health Insurance-State,Arthritis-State,Binge Drinking-State,High Blood Pressure-State,Take Blood Pressure Meds-State,Cancer Excl Skin Cancer-State,...,Air Polution-State,Diabetes Prevalence-State,% Food Insecure-State,% Limited Access-State,Drug Overdose Mortality Rate-State,Household Income-State,% < 18-State,% 65 and over-State,% Female-State,% Rural-State
0,Alabama,1,964856,345,16.764296,29.102380,14.724345,39.532320,77.935350,5.941826,...,10.97886209,13.699947,39694.52349,7.870497,14.455739,47404.18596,22.553061,16.132071,51.564041,40.568464
1,Alaska,2,291826,55,12.498273,19.711871,19.459278,26.678745,62.511725,5.074812,...,,7.064687,19383.74916,9.152489,14.816969,74702.03082,25.249834,10.406608,47.683631,31.227652
2,Arizona,4,3895587,1000,16.045813,22.834772,16.869777,27.066968,69.233917,5.582601,...,9.085653069,9.543486,399735.74880,7.390899,18.822692,54141.40487,23.538815,16.893839,50.326652,9.858951
3,Arkansas,5,490357,118,13.431531,24.727807,15.426193,34.381320,74.797332,5.868283,...,10.42924339,12.813615,22619.11386,8.600089,10.742482,45271.71853,23.594193,16.288273,50.878475,43.083007
4,California,6,22365173,5239,14.409413,17.704521,17.443133,26.479599,67.416362,5.049974,...,11.62161509,8.476884,454094.65080,3.286928,11.787608,69486.87590,23.166520,13.621994,50.335408,4.959325

In [6]:
all_df.head()

,Unnamed: 0,FIPS,State,County,% Smokers,% Obese,Food Environment Index,% Excessive Drinking,# Primary Care Physicians,PCP Rate,...,% Not Proficient in English,% Female,# Rural,% Rural,Teen Birth Rate,% LBW,# Associations_y,Association Rate_y,fips_state,fips_county
0,0,1001,Alabama,Autauga,19.124658,36.4,7.1,16.878015,25.0,45.16957,...,0.832739,51.288437,22921.0,42.002162,27.996758,8.594631,77.0,13.912226498,1,1001
1,1,1003,Alabama,Baldwin,16.795485,29.3,7.9,16.714969,148.0,72.65266,...,0.818809,51.457833,77060.0,42.279099,31.965138,8.480290,225.0,11.045167371,1,1003
2,2,1005,Alabama,Barbour,21.540878,44.2,5.5,12.698715,11.0,41.52667,...,1.519370,46.932409,18613.0,67.789635,50.189205,11.741294,21.0,7.9278190947,1,1005
3,3,1007,Alabama,Bibb,19.916404,38.4,7.6,15.925151,12.0,53.13732,...,0.448137,46.363114,15663.0,68.352607,47.260274,11.258278,24.0,10.627463136,1,1007
4,4,1009,Alabama,Blount,19.652158,35.8,8.5,15.378722,12.0,20.80696,...,1.878506,50.613476,51562.0,89.951502,39.624778,7.791667,51.0,8.8429594438,1,1009

# Load Dataframes into SQLITE Database

In [8]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///HealthIndicatorsData.db')
county_df.to_sql('county_data', con=engine, if_exists='replace',index_label="id")
state_df.to_sql('state_data', con=engine, if_exists='replace',index_label="id")
all_df.to_sql('county_health_rankings_data', con=engine, if_exists='replace',index_label="id")

In [9]:
engine.execute("SELECT * FROM county_data WHERE State='North Carolina' LIMIT 3").fetchall()

[(190, 'North Carolina', 'Buncombe', 37, 37021, 29, 83319, 13.83672872, 23.92842089, 15.48306389, 30.93961041, 77.04468489, 6.831984301, 8.288185168, 6.42139488, 73.8581356, 79.06613257, 67.30147625, 6.1743383860000005, 42.41845917, 34.77003565, 16.61965578, 63.74952892, 9.381227571, 34.53287125, 2.897819225, 19.67468885, 79.81517541, 11.77655157, 26.7023212, '86.90791656', 11.04912565, 30.20371824, 3.207656117, 14.70726365, 7.977552817, 16.44252839, 22.7, '7.5', 16.9802831, 24.34595325, 141.40249, 73.02176999999999, 90.40959041, 67.64909847, 3.8437293739999996, 19.4, 13.3107932, '8.9', 9.2, 34340, '7.993473178', '18.4257803', 50538, 256088, 18.94583112, 19.12779982, 52.072725, 24.07959114),
 (191, 'North Carolina', 'Cabarrus', 37, 37025, 22, 79057, 17.11802497, 22.43287881, 15.87011776, 32.25230024, 74.11672970000001, 5.9279077120000006, 8.471521812999999, 5.8140531520000005, 73.81412146, 78.07716964, 66.71449208, 6.4495351460000006, 39.19227519, 34.32602806, 19.67542912, 64.46604602, 9.763146843, 33.43179478, 2.7642106330000003, 23.83779172, 79.87315355, 13.10358855, 33.11528391, '86.02326802', 12.04610471, 32.82938007, 3.0768394960000003, 16.12857938, 8.867353119, 16.82894596, 31.0, '7.7', 17.2265921, 25.43946096, 90.97285, 42.66085, 89.57597173, 71.21745250000001, 4.52858938, 16.1, 10.8760838, '10.4', 9.7, 24710, '7.231018176', '16.59736983', 63059, 201590, 25.98194355, 12.91730741, 51.36613919, 19.25330457),
 (192, 'North Carolina', 'Chatham', 37, 37037, 1, 1422, 6.5, 38.2, 9.1, 46.7, 88.0, 13.1, 7.2, 9.9, 84.9, 93.5, 80.7, 7.0, 47.4, 42.8, 9.2, 80.3, 13.4, 48.6, 3.7, 17.6, 78.1, 7.2, 25.9, '85.9', 10.6, 24.8, 3.8, 7.1, 8.834161771, 15.20401131, 25.6, '8.5', 16.10723978, 24.29493714, 90.23235, 47.06338, 89.73799127, 69.76190476, 4.23971482, 17.4, 9.446198962, '9', 11.8, 7730, '2.403916075', '5.663877207', 63303, 72243, 19.82475811, 25.66477029, 52.23897125, 65.92236832)]

In [10]:
engine.execute("SELECT * FROM state_data WHERE State='Tennessee' LIMIT 3").fetchall()

[(42, 'Tennessee', 47, 1835967, 511, 17.12457953, 26.78341539, 14.31076228, 36.797707200000005, 76.15711388, 5.3628507480000005, 11.00711701, 6.193261317, 70.38716758, 74.09604677, 63.02211548, 8.083160917, 28.30072311, 31.91733615, 23.55547943, 56.83132279, 11.90143429, 35.8094829, 3.066658987, 28.64573731, 80.73442949, 15.09132751, 35.56291872, '83.88926887', 14.80839912, 40.15617884, 3.722597247, 19.49124728, 6651194, 95, 9.024791501000001, 20.88366516, 32.34417804, 7.207873113, 14.68418541, 35.73203262, 72.40417123, 52.817584100000005, 86.58883273, 62.89266857, 4.898325836000001, 22.76851928, 11.32231119, '10.13093709', 12.72744358, 54563.98774, 8.429296265, 21.52805933, 50440.38166, 22.57932937, 15.74231634, 51.249129100000005, 33.01639955)]

In [13]:
engine.execute("SELECT * FROM county_health_rankings_data WHERE State='Tennessee' LIMIT 3").fetchall()

[(2428, 2428, 47001, 'Tennessee', 'Anderson', 18.310864236, 4.4592577492, 4.4646286182, 13.73647771, 49.0, 64.68732, '1546:1', '3', 65.63643865899999, '2', 988.0, 87.854251012, 85.365853659, 87.961985216, 717.0, 63.877266388, None, None, 1681.0, 33901.0, 4.9585557948000005, 21.6, 25.0, 40.028901734, 27.480623129, None, None, 10840, 14.4, 7031.4634535, 9.3591868034, 75.0, 33.00867468, 46731.0, 32600.0, 36304.0, 45104.0, 75936, 20.858354404, 19.716603455999998, 3003, 3.9546460177, 309, 0.4069216182, 1142, 1.5038980194, 45, 0.05926042980000001, 2058, 2.7101769912, 68003, 89.553044669, 620, 0.8675696854, 51.399863043, 26041.0, 34.661715183000005, 12.554112554000001, 8800.7874821, None, None, 47, 47001),
 (2429, 2429, 47003, 'Tennessee', 'Bedford', 20.804671914, 4.6161668571, 4.5274713569, 14.593471460999998, 16.0, 33.91052, '2949:1', '2', 51.930844689, '3', 660.0, 86.96969697, 89.36170212799999, 86.78629690000001, 429.0, 66.433566434, 54.838709677, 67.336683417, 1003.0, 19812.0, 5.0625883303, 22.5, 27.064220183000003, 31.75087108, 17.119801366, 67.336683417, None, 6080, 13.2, 2983.991309, 6.622556059, 22.0, 15.570370999000001, 47295.0, 33883.0, 32476.0, 46264.0, 47484, 25.665487321999997, 15.082975317999999, 3500, 7.3709038834000005, 510, 1.0740459944, 607, 1.2783253306, 77, 0.16215988539999998, 5597, 11.787128295999999, 36824, 77.550332744, 1397, 3.2326738401, 50.840283043, 25053.0, 55.60166896, 14.379084967, 8271.472148, 67.336683417, None, 47, 47003),
 (2430, 2430, 47005, 'Tennessee', 'Benton', 20.375489363, 5.0087649293, 4.8739439224000005, 12.204854252999999, 3.0, 18.60004, '5376:1', '4', 46.612893443999994, '3', 459.0, 88.671023965, 100.0, 88.36689038, 289.0, 49.826989618999995, None, None, 492.0, 6747.0, 7.2921298355, 30.1, None, None, None, None, None, 2550, 15.7, 1082.3638586, 6.564157065700001, 19.0, 39.347249834, 35723.0, 21250.0, 41528.0, 34076.0, 16014, 19.757712002, 23.292119396, 390, 2.4353690521, 88, 0.5495191707, 96, 0.599475459, 3, 0.0187336081, 366, 2.2855001873, 14866, 92.83127263600001, 211, 1.3692407528, 50.693143498999994, 12937.0, 78.458366184, None, 10737.935759, None, None, 47, 47005)]